In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('titanic.txt')

In [2]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
data = data.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')

In [4]:
age_mean = data['Age'].mean()
data['Age'] = data['Age'].fillna(age_mean)

In [5]:
data.isnull().values.any()

False

In [6]:
data.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [7]:
sex_dummies = pd.get_dummies(data['Sex'])
data = pd.concat([data,sex_dummies],axis='columns')

In [8]:
data.head()

Survived  Pclass     Sex   Age     Fare  female  male
0         0       3    male  22.0   7.2500       0     1
1         1       1  female  38.0  71.2833       1     0
2         1       3  female  26.0   7.9250       1     0
3         1       1  female  35.0  53.1000       1     0
4         0       3    male  35.0   8.0500       0     1

In [9]:
data = data.drop('Sex',axis='columns')

In [10]:
data.head()

Survived  Pclass   Age     Fare  female  male
0         0       3  22.0   7.2500       0     1
1         1       1  38.0  71.2833       1     0
2         1       3  26.0   7.9250       1     0
3         1       1  35.0  53.1000       1     0
4         0       3  35.0   8.0500       0     1

In [11]:
y = data['Survived']
X = data.drop('Survived',axis='columns')

In [12]:
print(X.shape, y.shape)

(891, 5) (891,)


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=1234)

In [14]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [15]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [16]:
model.score(X_test,y_test)

0.8100558659217877

In [17]:
from sklearn.preprocessing import Normalizer
Scaler = Normalizer()
normalize_X_train = Scaler.fit_transform(X_train)

In [21]:
print(normalize_X_train)

[[0.17916409 0.71665638 0.67136966 0.         0.05972136]
 [0.00659807 0.00607023 0.99993804 0.         0.00659807]
 [0.05815918 0.98870603 0.13675549 0.         0.01938639]
 ...
 [0.11781989 0.94255914 0.3100941  0.         0.0392733 ]
 [0.03867669 0.96691724 0.25139848 0.         0.01933834]
 [0.03363292 0.99886819 0.         0.         0.03363292]]


In [19]:
model2 = DecisionTreeClassifier()
model2.fit(normalize_X_train,y_train)

DecisionTreeClassifier()

In [20]:
normalize_X_test = Scaler.fit_transform(X_test)
model2.score(normalize_X_test,y_test)

0.7653631284916201

In [22]:
print(X_train)

     Pclass        Age      Fare  female  male
125       3  12.000000   11.2417       0     1
305       1   0.920000  151.5500       0     1
631       3  51.000000    7.0542       0     1
643       3  29.699118   56.4958       0     1
808       2  39.000000   13.0000       0     1
..      ...        ...       ...     ...   ...
204       3  18.000000    8.0500       0     1
53        2  29.000000   26.0000       1     0
294       3  24.000000    7.8958       0     1
723       2  50.000000   13.0000       0     1
815       1  29.699118    0.0000       0     1

[712 rows x 5 columns]
